/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mocks from "./mocks";
export { Payroll__factory } from "./Payroll__factory";
export { PayrollConfidentialWrapper__factory } from "./PayrollConfidentialWrapper__factory";
export { PayrollFactoryRegistry__factory } from "./PayrollFactoryRegistry__factory";
