/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { Payroll } from "./Payroll";
export type { PayrollConfidentialWrapper } from "./PayrollConfidentialWrapper";
export type { PayrollFactoryRegistry } from "./PayrollFactoryRegistry";
