/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PayrollInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "EMPLOYER_ROLE"
      | "MAX_BATCH_SIZE"
      | "addEmployee"
      | "companyRef"
      | "confidentialProtocolId"
      | "deactivate"
      | "deactivated"
      | "employer"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isEmployee"
      | "lastPaymentOfEmployee"
      | "lastRunIdOfEmployee"
      | "myEmploymentActive"
      | "myLastPayment"
      | "myLastRunId"
      | "mySalary"
      | "myWrapperOperatorApproved"
      | "paidInRun"
      | "payrollHasOperatorApproval"
      | "payrollToken"
      | "removeEmployee"
      | "renounceRole"
      | "requestUnwrap"
      | "revokeRole"
      | "runPayrollBatchForRun"
      | "runPayrollForRun"
      | "salaryOfEmployee"
      | "setSalary"
      | "supportsInterface"
      | "token"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PayrollDeactivated"
      | "PayrollRunExecuted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMPLOYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "companyRef",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivated",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "employer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPaymentOfEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRunIdOfEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "myEmploymentActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "myLastPayment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "myLastRunId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mySalary", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "myWrapperOperatorApproved",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "paidInRun",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "payrollHasOperatorApproval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payrollToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestUnwrap",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "runPayrollBatchForRun",
    values: [AddressLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "runPayrollForRun",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "salaryOfEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSalary",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMPLOYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "companyRef", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deactivate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isEmployee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastPaymentOfEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRunIdOfEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myEmploymentActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myLastPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myLastRunId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mySalary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "myWrapperOperatorApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paidInRun", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payrollHasOperatorApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payrollToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUnwrap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "runPayrollBatchForRun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "runPayrollForRun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "salaryOfEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSalary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
}

export namespace PayrollDeactivatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollRunExecutedEvent {
  export type InputTuple = [runId: BytesLike, employeeCount: BigNumberish];
  export type OutputTuple = [runId: string, employeeCount: bigint];
  export interface OutputObject {
    runId: string;
    employeeCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Payroll extends BaseContract {
  connect(runner?: ContractRunner | null): Payroll;
  waitForDeployment(): Promise<this>;

  interface: PayrollInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EMPLOYER_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  addEmployee: TypedContractMethod<
    [employee_: AddressLike],
    [void],
    "nonpayable"
  >;

  companyRef: TypedContractMethod<[], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  deactivate: TypedContractMethod<[], [void], "nonpayable">;

  deactivated: TypedContractMethod<[], [boolean], "view">;

  employer: TypedContractMethod<[], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isEmployee: TypedContractMethod<[employee_: AddressLike], [boolean], "view">;

  lastPaymentOfEmployee: TypedContractMethod<
    [employee_: AddressLike],
    [string],
    "view"
  >;

  lastRunIdOfEmployee: TypedContractMethod<
    [employee_: AddressLike],
    [string],
    "view"
  >;

  myEmploymentActive: TypedContractMethod<[], [boolean], "view">;

  myLastPayment: TypedContractMethod<[], [string], "view">;

  myLastRunId: TypedContractMethod<[], [string], "view">;

  mySalary: TypedContractMethod<[], [string], "view">;

  myWrapperOperatorApproved: TypedContractMethod<[], [boolean], "view">;

  paidInRun: TypedContractMethod<
    [employee_: AddressLike, runId: BytesLike],
    [boolean],
    "view"
  >;

  payrollHasOperatorApproval: TypedContractMethod<[], [boolean], "view">;

  payrollToken: TypedContractMethod<[], [string], "view">;

  removeEmployee: TypedContractMethod<
    [employee_: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestUnwrap: TypedContractMethod<
    [to: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  runPayrollBatchForRun: TypedContractMethod<
    [employees_: AddressLike[], runId: BytesLike],
    [void],
    "nonpayable"
  >;

  runPayrollForRun: TypedContractMethod<
    [employee_: AddressLike, runId: BytesLike],
    [string],
    "nonpayable"
  >;

  salaryOfEmployee: TypedContractMethod<
    [employee_: AddressLike],
    [string],
    "view"
  >;

  setSalary: TypedContractMethod<
    [employee_: AddressLike, encryptedSalary: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  token: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EMPLOYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addEmployee"
  ): TypedContractMethod<[employee_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "companyRef"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivated"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "employer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isEmployee"
  ): TypedContractMethod<[employee_: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPaymentOfEmployee"
  ): TypedContractMethod<[employee_: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "lastRunIdOfEmployee"
  ): TypedContractMethod<[employee_: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "myEmploymentActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "myLastPayment"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "myLastRunId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mySalary"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "myWrapperOperatorApproved"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paidInRun"
  ): TypedContractMethod<
    [employee_: AddressLike, runId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "payrollHasOperatorApproval"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payrollToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeEmployee"
  ): TypedContractMethod<[employee_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestUnwrap"
  ): TypedContractMethod<
    [to: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "runPayrollBatchForRun"
  ): TypedContractMethod<
    [employees_: AddressLike[], runId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "runPayrollForRun"
  ): TypedContractMethod<
    [employee_: AddressLike, runId: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "salaryOfEmployee"
  ): TypedContractMethod<[employee_: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "setSalary"
  ): TypedContractMethod<
    [employee_: AddressLike, encryptedSalary: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PayrollDeactivated"
  ): TypedContractEvent<
    PayrollDeactivatedEvent.InputTuple,
    PayrollDeactivatedEvent.OutputTuple,
    PayrollDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PayrollRunExecuted"
  ): TypedContractEvent<
    PayrollRunExecutedEvent.InputTuple,
    PayrollRunExecutedEvent.OutputTuple,
    PayrollRunExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "PayrollDeactivated()": TypedContractEvent<
      PayrollDeactivatedEvent.InputTuple,
      PayrollDeactivatedEvent.OutputTuple,
      PayrollDeactivatedEvent.OutputObject
    >;
    PayrollDeactivated: TypedContractEvent<
      PayrollDeactivatedEvent.InputTuple,
      PayrollDeactivatedEvent.OutputTuple,
      PayrollDeactivatedEvent.OutputObject
    >;

    "PayrollRunExecuted(bytes32,uint256)": TypedContractEvent<
      PayrollRunExecutedEvent.InputTuple,
      PayrollRunExecutedEvent.OutputTuple,
      PayrollRunExecutedEvent.OutputObject
    >;
    PayrollRunExecuted: TypedContractEvent<
      PayrollRunExecutedEvent.InputTuple,
      PayrollRunExecutedEvent.OutputTuple,
      PayrollRunExecutedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
