/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PayrollFactoryRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "companyOfEmployer"
      | "companyRefOfPayroll"
      | "deleteCompany"
      | "isRegisteredPayroll"
      | "myCompany"
      | "registerCompany"
      | "token"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PayrollDeleted" | "PayrollDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "companyOfEmployer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "companyRefOfPayroll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteCompany",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredPayroll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "myCompany", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerCompany",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "companyOfEmployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "companyRefOfPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "myCompany", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
}

export namespace PayrollDeletedEvent {
  export type InputTuple = [payroll: AddressLike, companyRef: BytesLike];
  export type OutputTuple = [payroll: string, companyRef: string];
  export interface OutputObject {
    payroll: string;
    companyRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayrollDeployedEvent {
  export type InputTuple = [payroll: AddressLike, companyRef: BytesLike];
  export type OutputTuple = [payroll: string, companyRef: string];
  export interface OutputObject {
    payroll: string;
    companyRef: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayrollFactoryRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PayrollFactoryRegistry;
  waitForDeployment(): Promise<this>;

  interface: PayrollFactoryRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  companyOfEmployer: TypedContractMethod<
    [employer_: AddressLike],
    [string],
    "view"
  >;

  companyRefOfPayroll: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  deleteCompany: TypedContractMethod<[], [void], "nonpayable">;

  isRegisteredPayroll: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  myCompany: TypedContractMethod<[], [string], "view">;

  registerCompany: TypedContractMethod<
    [companyRef: BytesLike],
    [string],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "companyOfEmployer"
  ): TypedContractMethod<[employer_: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "companyRefOfPayroll"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "deleteCompany"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isRegisteredPayroll"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "myCompany"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerCompany"
  ): TypedContractMethod<[companyRef: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PayrollDeleted"
  ): TypedContractEvent<
    PayrollDeletedEvent.InputTuple,
    PayrollDeletedEvent.OutputTuple,
    PayrollDeletedEvent.OutputObject
  >;
  getEvent(
    key: "PayrollDeployed"
  ): TypedContractEvent<
    PayrollDeployedEvent.InputTuple,
    PayrollDeployedEvent.OutputTuple,
    PayrollDeployedEvent.OutputObject
  >;

  filters: {
    "PayrollDeleted(address,bytes32)": TypedContractEvent<
      PayrollDeletedEvent.InputTuple,
      PayrollDeletedEvent.OutputTuple,
      PayrollDeletedEvent.OutputObject
    >;
    PayrollDeleted: TypedContractEvent<
      PayrollDeletedEvent.InputTuple,
      PayrollDeletedEvent.OutputTuple,
      PayrollDeletedEvent.OutputObject
    >;

    "PayrollDeployed(address,bytes32)": TypedContractEvent<
      PayrollDeployedEvent.InputTuple,
      PayrollDeployedEvent.OutputTuple,
      PayrollDeployedEvent.OutputObject
    >;
    PayrollDeployed: TypedContractEvent<
      PayrollDeployedEvent.InputTuple,
      PayrollDeployedEvent.OutputTuple,
      PayrollDeployedEvent.OutputObject
    >;
  };
}
